INSERT INTO books(title,code,shelfmark,author) VALUES('Encyclopaedia Britannica','AE5.E363','B2.1411','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The Encyclopaedia Britannica: the twelfth edition.','AE5.E363','B2.1412','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The Encyclopaedia Britannica: the thirteenth edition.','AE5.E363','B2.1413','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The New Encyclopaedia Britannica','AE5.E363','B2.1415','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Grote Winkler Prins encyclopaedie','AE19.G88','B2.1383','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Brockhaus, die Enzyklopadie : in vierundzwanzig Banden','AE27.G672','B2.1395','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Enciclopedia italiana di scienze, lettere ed arti','AE35.E5','B2.1482','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Bonniers Lexikon','AE45.B622','B2.1488','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The Penguin dictionary of proper names','AG5','B2.1506BB','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The Guinness book of answers','AG6.G83','B2.1490A','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Guinness world records','AG243.G87','B2.1490','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The Athenaeum subject index to periodicals.','AI3.A68','B1.1074','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The subject index to periodicals.','AI3.A72','B1.1074','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Titles in series','AI3.B3','B1.200','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('An author index to selected British "little magazines," 1930-1939','AI3.B56','B1.989','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('British humanities index','AI3.B7','B1.1074','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Essay and general literature index','AI3.E752','B1.1095','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Humanities index','AI3.H85','B1.991','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Index to Commonwealth little magazines','AI3.I48','B1.988','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('An index to periodical literature. (To 1882)','AI3.P7','B1.1066','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Nineteenth century readers'' guide to periodical literature, 1890-1899','AI3.R496','B1.1070','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Index to the periodicals of...','AI3.R5','B1.1072','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Cumulative author index for Poole''s index to periodical literature, 1802-1906','AI3.W3','B1.1067','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The Wellesley index to Victorian periodicals, 1824-1900','AI3.W45','B1.1068','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Times index','AI21.T46','B1.1287','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The directory of museums & living displays','AM1.H78','B2.7A','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('World museum publications','AM1.W67','B2.8A','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The Cambridge guide to the museums of Britain and Ireland','AM41.H79','B2.7B','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('A.S.K. Hollis...','AS118','B2.714','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Centres, bureaux & research institutes.','AS118.C39.3','B2.978','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Councils, committees & boards','AS118.C68','B2.975','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Directory of British associations & associations in Ireland.','AS118.D56','B2.977','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The British Academy directory','AS122','B2.15','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Bibliographie analytique des biographies collectives ...1789-1985','AS162.B6','B3.524','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The world of learning','AS2.W6','B2.110','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Encyclopedia of associations.','AS22.E5','B2.96','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Research centers directory.','AS25.D5','B2.94','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Encyclopedia of associations. International organizations','AS8.E53','B2.97','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Buttress''s World guide to abbreviations of organizations.','AS8.P58','B2.693','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('International encyclopedia of abbreviations and acronyms of organizations','AS8.W46','B2.688','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The international foundation directory 2003.','AS911.A2','B2.679B','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Directory of grant-making trusts.','AS911.A2','B2.678','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Hinduja Foundation encyclopaedia of Nobel laureates 1901-1987','AS911.H56','B3.56','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Whitaker''s obituary almanack.','AY754','B3.19','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Whitaker''s almanack','AY754.W5','B2.1390','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('International dictionary of graphic symbols','AZ108.A76','B2.1498','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Directory of American philosophers.','B935.D5','B3.969','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Internationales Abkurzungsverzeichnis fur Theologie...','BR95.5','S394B1.1211IATG3','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The Catholic directory of England and Wales.','BX1491.A1','B2.816','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The Catholic directory for Scotland.','BX1497.A3','B2.816A','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Irish Catholic directory for ...','BX1503.A3','B2.816B','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Obit Book of the English Benedictines from 1600 to 1912','BX3016.S6','B3.176','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Obituary notices of the English Dominicans from 1555 to 1952','BX3550.','E5B3.178','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The Book of saints','BX4655','B2.1496','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Series episcoporum ecclesiae catholicae','BX4666.G3','B2.1489','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The seminary priests : a dictionary of the secular clergy...1558-1850','BX4676.A52','B3.175','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('English and Welsh priests, 1558-1800 : a working list','BX4676.E54','B3.174','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('English and Welsh priests, 1801-1914 : a working list','BX4676.E54','B3.174A','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Biographies of English Catholics in the eighteenth century','BX4676.K5','B3.173','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Les eveques et les archeveques de France depuis 1682 jusqu''...1801','BX4682.J43','B3.530','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Biografisch lexicon voor de geschiedenis van het Nederlandse protestantisme','BX4846.B56','B3.756','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The Church of England year book','BX5015.C45','B2.806c','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Crockford''s clerical directory.','BX5031.C8','B2.806','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Index ecclesiasticus','BX5031.F7','B3.161','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The Oxford Diocesan year book.','BX5107.O808','B2.806D','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Scottish Episcopal clergy, 1689-2000','BX5390.S36','B3.175A','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Church of Ireland directory','BX5440.A3','B2.817','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The Baptist Union directory for ...','BX6276.A1','B2.809','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Garlick''s Methodist registry, 1983','BX8213.G23','B2.812','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The minutes of the annual conference ... / the Methodist Church.','BX8350.M4','B2.811','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Annuario pontificio per l''anno ...','BX845.A75','B2.815','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The Oxford dictionary of popes','BX955.2.K45','B3.170','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The Church of Scotland year-book...','BX9076','B2.813','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The United Reformed Church year book.','BX9890.U25','B2.810','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('British archives : a guide to archive resources in the United Kingdom','CD1040.F67','B2.12','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('A hand-book of mottoes : borne by the nobility, gentry, cities, public companies','CR75.G7','B2.681','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Titles and forms of address : a guide to correct use.','CR3890.T56','B2.699','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('Debrett''s correct form.','CR3891.M65','B2.700','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The Royalty, peerage and nobility of the world','CS404.R68','B3.31','John Doe');
INSERT INTO books(title,code,shelfmark,author) VALUES('The titled nobility of Europe','CS404.R8','B3.30','John Doe');

