<?php
class ContentForBooksMigration extends ApplicationMigration {
	function up(){
		Book::CreateNewRecord(['title' => 'Encyclopaedia Britannica', 'code' => 'AE5.E363', 'shelfmark' => 'B2.1411', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The Encyclopaedia Britannica: the twelfth edition.', 'code' => 'AE5.E363', 'shelfmark' => 'B2.1412', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The Encyclopaedia Britannica: the thirteenth edition.', 'code' => 'AE5.E363', 'shelfmark' => 'B2.1413', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The New Encyclopaedia Britannica', 'code' => 'AE5.E363', 'shelfmark' => 'B2.1415', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Grote Winkler Prins encyclopaedie', 'code' => 'AE19.G88', 'shelfmark' => 'B2.1383', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Brockhaus, die Enzyklopadie : in vierundzwanzig Banden', 'code' => 'AE27.G672', 'shelfmark' => 'B2.1395', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Enciclopedia italiana di scienze, lettere ed arti', 'code' => 'AE35.E5', 'shelfmark' => 'B2.1482', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Bonniers Lexikon', 'code' => 'AE45.B622', 'shelfmark' => 'B2.1488', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The Penguin dictionary of proper names', 'code' => 'AG5', 'shelfmark' => 'B2.1506BB', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The Guinness book of answers', 'code' => 'AG6.G83', 'shelfmark' => 'B2.1490A', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Guinness world records', 'code' => 'AG243.G87', 'shelfmark' => 'B2.1490', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The Athenaeum subject index to periodicals.', 'code' => 'AI3.A68', 'shelfmark' => 'B1.1074', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The subject index to periodicals.', 'code' => 'AI3.A72', 'shelfmark' => 'B1.1074', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Titles in series', 'code' => 'AI3.B3', 'shelfmark' => 'B1.200', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'An author index to selected British "little magazines," 1930-1939', 'code' => 'AI3.B56', 'shelfmark' => 'B1.989', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'British humanities index', 'code' => 'AI3.B7', 'shelfmark' => 'B1.1074', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Essay and general literature index', 'code' => 'AI3.E752', 'shelfmark' => 'B1.1095', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Humanities index', 'code' => 'AI3.H85', 'shelfmark' => 'B1.991', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Index to Commonwealth little magazines', 'code' => 'AI3.I48', 'shelfmark' => 'B1.988', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'An index to periodical literature. (To 1882)', 'code' => 'AI3.P7', 'shelfmark' => 'B1.1066', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Nineteenth century readers\' guide to periodical literature, 1890-1899', 'code' => 'AI3.R496', 'shelfmark' => 'B1.1070', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Index to the periodicals of...', 'code' => 'AI3.R5', 'shelfmark' => 'B1.1072', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Cumulative author index for Poole\'s index to periodical literature, 1802-1906', 'code' => 'AI3.W3', 'shelfmark' => 'B1.1067', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The Wellesley index to Victorian periodicals, 1824-1900', 'code' => 'AI3.W45', 'shelfmark' => 'B1.1068', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Times index', 'code' => 'AI21.T46', 'shelfmark' => 'B1.1287', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The directory of museums & living displays', 'code' => 'AM1.H78', 'shelfmark' => 'B2.7A', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'World museum publications', 'code' => 'AM1.W67', 'shelfmark' => 'B2.8A', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The Cambridge guide to the museums of Britain and Ireland', 'code' => 'AM41.H79', 'shelfmark' => 'B2.7B', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'A.S.K. Hollis...', 'code' => 'AS118', 'shelfmark' => 'B2.714', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Centres, bureaux & research institutes.', 'code' => 'AS118.C39.3', 'shelfmark' => 'B2.978', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Councils, committees & boards', 'code' => 'AS118.C68', 'shelfmark' => 'B2.975', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Directory of British associations & associations in Ireland.', 'code' => 'AS118.D56', 'shelfmark' => 'B2.977', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The British Academy directory', 'code' => 'AS122', 'shelfmark' => 'B2.15', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Bibliographie analytique des biographies collectives ...1789-1985', 'code' => 'AS162.B6', 'shelfmark' => 'B3.524', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The world of learning', 'code' => 'AS2.W6', 'shelfmark' => 'B2.110', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Encyclopedia of associations.', 'code' => 'AS22.E5', 'shelfmark' => 'B2.96', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Research centers directory.', 'code' => 'AS25.D5', 'shelfmark' => 'B2.94', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Encyclopedia of associations. International organizations', 'code' => 'AS8.E53', 'shelfmark' => 'B2.97', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Buttress\'s World guide to abbreviations of organizations.', 'code' => 'AS8.P58', 'shelfmark' => 'B2.693', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'International encyclopedia of abbreviations and acronyms of organizations', 'code' => 'AS8.W46', 'shelfmark' => 'B2.688', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The international foundation directory 2003.', 'code' => 'AS911.A2', 'shelfmark' => 'B2.679B', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Directory of grant-making trusts.', 'code' => 'AS911.A2', 'shelfmark' => 'B2.678', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Hinduja Foundation encyclopaedia of Nobel laureates 1901-1987', 'code' => 'AS911.H56', 'shelfmark' => 'B3.56', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Whitaker\'s obituary almanack.', 'code' => 'AY754', 'shelfmark' => 'B3.19', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Whitaker\'s almanack', 'code' => 'AY754.W5', 'shelfmark' => 'B2.1390', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'International dictionary of graphic symbols', 'code' => 'AZ108.A76', 'shelfmark' => 'B2.1498', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Directory of American philosophers.', 'code' => 'B935.D5', 'shelfmark' => 'B3.969', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Internationales Abkurzungsverzeichnis fur Theologie...', 'code' => 'BR95.5', 'shelfmark' => 'S394B1.1211IATG3', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The Catholic directory of England and Wales.', 'code' => 'BX1491.A1', 'shelfmark' => 'B2.816', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The Catholic directory for Scotland.', 'code' => 'BX1497.A3', 'shelfmark' => 'B2.816A', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Irish Catholic directory for ...', 'code' => 'BX1503.A3', 'shelfmark' => 'B2.816B', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Obit Book of the English Benedictines from 1600 to 1912', 'code' => 'BX3016.S6', 'shelfmark' => 'B3.176', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Obituary notices of the English Dominicans from 1555 to 1952', 'code' => 'BX3550.', 'shelfmark' => 'E5B3.178', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The Book of saints', 'code' => 'BX4655', 'shelfmark' => 'B2.1496', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Series episcoporum ecclesiae catholicae', 'code' => 'BX4666.G3', 'shelfmark' => 'B2.1489', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The seminary priests : a dictionary of the secular clergy...1558-1850', 'code' => 'BX4676.A52', 'shelfmark' => 'B3.175', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'English and Welsh priests, 1558-1800 : a working list', 'code' => 'BX4676.E54', 'shelfmark' => 'B3.174', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'English and Welsh priests, 1801-1914 : a working list', 'code' => 'BX4676.E54', 'shelfmark' => 'B3.174A', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Biographies of English Catholics in the eighteenth century', 'code' => 'BX4676.K5', 'shelfmark' => 'B3.173', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Les eveques et les archeveques de France depuis 1682 jusqu\'...1801', 'code' => 'BX4682.J43', 'shelfmark' => 'B3.530', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Biografisch lexicon voor de geschiedenis van het Nederlandse protestantisme', 'code' => 'BX4846.B56', 'shelfmark' => 'B3.756', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The Church of England year book', 'code' => 'BX5015.C45', 'shelfmark' => 'B2.806c', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Crockford\'s clerical directory.', 'code' => 'BX5031.C8', 'shelfmark' => 'B2.806', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Index ecclesiasticus', 'code' => 'BX5031.F7', 'shelfmark' => 'B3.161', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The Oxford Diocesan year book.', 'code' => 'BX5107.O808', 'shelfmark' => 'B2.806D', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Scottish Episcopal clergy, 1689-2000', 'code' => 'BX5390.S36', 'shelfmark' => 'B3.175A', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Church of Ireland directory', 'code' => 'BX5440.A3', 'shelfmark' => 'B2.817', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The Baptist Union directory for ...', 'code' => 'BX6276.A1', 'shelfmark' => 'B2.809', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Garlick\'s Methodist registry, 1983', 'code' => 'BX8213.G23', 'shelfmark' => 'B2.812', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The minutes of the annual conference ... / the Methodist Church.', 'code' => 'BX8350.M4', 'shelfmark' => 'B2.811', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Annuario pontificio per l\'anno ...', 'code' => 'BX845.A75', 'shelfmark' => 'B2.815', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The Oxford dictionary of popes', 'code' => 'BX955.2.K45', 'shelfmark' => 'B3.170', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The Church of Scotland year-book...', 'code' => 'BX9076', 'shelfmark' => 'B2.813', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The United Reformed Church year book.', 'code' => 'BX9890.U25', 'shelfmark' => 'B2.810', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'British archives : a guide to archive resources in the United Kingdom', 'code' => 'CD1040.F67', 'shelfmark' => 'B2.12', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'A hand-book of mottoes : borne by the nobility, gentry, cities, public companies', 'code' => 'CR75.G7', 'shelfmark' => 'B2.681', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Titles and forms of address : a guide to correct use.', 'code' => 'CR3890.T56', 'shelfmark' => 'B2.699', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'Debrett\'s correct form.', 'code' => 'CR3891.M65', 'shelfmark' => 'B2.700', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The Royalty, peerage and nobility of the world', 'code' => 'CS404.R68', 'shelfmark' => 'B3.31', 'author' => 'John Doe']);
		Book::CreateNewRecord(['title' => 'The titled nobility of Europe', 'code' => 'CS404.R8', 'shelfmark' => 'B3.30', 'author' => 'John Doe']);
	}
}
