development:
  database: atk14_demo
  host: 127.0.0.1
  username: atk14_demo
  password: demo

test:
  database: atk14_demo
  host: 127.0.0.1
  username: atk14_demo
  password: demo

production:
  database: atk14_demo
  host: 127.0.0.1
  username: atk14_demo
  password: <?=sha1(SECRET_TOKEN."Very_Sophisticated_Production_Password_Hiding")?>
