# This is a recipe how to deploy this application to our production environment
#
# You can run the deployment process by typing
#  $ ./scripts/deploy production
#
# or just
#  $ ./scripts/deploy
#

production:
  url: "http://www.atk14.net/"
  server: "cloudkicker.plovarna.cz"                                         # we are deploying on this server
  user: "devel"                                                             # we are deploying as this user
  directory: "/home/{{user}}/apps/www.atk14.net/production/"                # in this directory is this application installed on the server
  deploy_repository: "{{user}}@{{server}}:apps/www.atk14.net/repos/production.git"  # this is the URL of deployment git repository with a proper post-receive hook
  before_deploy:
  - "@local composer update --dev"
  - "@local NODE_OPTIONS=--use-openssl-ca bower update"
  - "@local gulp"
  rsync: 
  - "public/dist/"
  - "vendor/"
  after_deploy:
  - "./scripts/migrate && ./scripts/delete_temporary_files dbmole_cache"

# You can have another stage to deploy application on it (eg. preview).
# In this recipe you can mention only items which differ from the first recipe.
#
# preview:
#   server: server.example.com
#   user: deploy
#   directory: /home/deploy/previews/atk14skelet/
#   deploy_repository: deploy@server.example.com:repos/atk14skelet.git

# vim: set et:
